### ISSUE TITLE
Cannot home when out of limits

### ISSUE THREAD

**Issue by DSuds** [nortd/driveboardapp#12]
We are seeing an issue where if a limit is hit the home command is not issued.

First fix was not to clear the tx buffer on endstop errors, but even then we sill see the command issued but no motion on the machine.  (14.01/BBB)

Best solution to date has been reseting the Arduino and sending the home immediately.

**Comment by stefanix** [comment]
implemented currently in alpha, will eventually go into the master and packaged as binaries
